[package]
name = "binding_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.13.1"
napi-derive = "2"

[build-dependencies]
napi-build = "1"
